#!/usr/bin/python

import os
import urllib2
import re
import shutil
import subprocess
import sys
import tempfile

devnull = open(os.devnull, "w")

def list_repositories(url):
  try:
    response = urllib2.urlopen(url)
    return [m.group(1) for m in re.finditer(r"<b>(.+)</b>", response.read())]
  finally:
    response.close()

def access_allowed(temp_repo, repository_base, repository):
  output = subprocess.call(
    ["hg", "summary", "-R", temp_repo, "--remote", "--config",
     "paths.default=%s/%s" % (repository_base, repository)],
    stdout=devnull, stderr=devnull
  )
  return output == 0

if __name__ == "__main__":
  if len(sys.argv) != 3:
    print >>sys.stderr, "Usage: hg-check-access https://hg.adblockplus.org ssh://hg@ssh.adblockplus.org"
    sys.exit(1)

  hgweb_url, repository_base = sys.argv[1:3]

  temp_repo = tempfile.mkdtemp()
  subprocess.call(["hg", "init", temp_repo])

  for repository in list_repositories(hgweb_url):
    print repository, access_allowed(temp_repo, repository_base, repository)

  shutil.rmtree(temp_repo)
